# NOTE: This workflow is overkill for most R packages
# check-standard.yaml is likely a better choice
# usethis::use_github_action("check-standard") will install it.
#
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron:  '20 2 * * *'

name: rcc

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}${{ matrix.config.os-version }}

    name: ${{ matrix.config.os }}${{ matrix.config.os-version }} (${{ matrix.config.r }}) ${{ matrix.config.desc }}

    # Begin custom: services
    # End custom: services

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,               os-nick: all,    r: 'release'}
          - {os: windows-latest,             os-nick: all,    r: 'release'}
          - {os: windows-latest,             os-nick: all,    r: 'oldrel'}
          - {os: ubuntu-, os-version: 20.04, os-nick: focal,  r: 'release'}
          - {os: ubuntu-, os-version: 18.04, os-nick: bionic, r: 'release'}
          - {os: ubuntu-, os-version: 16.04, os-nick: xenial, r: 'release'}
          - {os: ubuntu-, os-version: 16.04, os-nick: xenial, r: 'devel', http-user-agent: "R/4.0.0 (ubuntu-16.04) R (4.0.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }
          - {os: ubuntu-, os-version: 16.04, os-nick: xenial, r: 'oldrel'}

          # Begin custom: R 3.5
          - {os: ubuntu-, os-version: 16.04, os-nick: xenial, r: '3.5'}
          # End custom: R 3.5

          # Begin custom: R 3.4
          - {os: ubuntu-, os-version: 16.04, os-nick: xenial, r: '3.4'}
          # End custom: R 3.4

          # Begin custom: R 3.3
          - {os: ubuntu-, os-version: 16.04, os-nick: xenial, r: '3.3'}
          # End custom: R 3.3

          # Begin custom: matrix elements
          # End custom: matrix elements
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/${{matrix.config.os-nick}}/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      # Begin custom: env vars
      # End custom: env vars

    steps:
      - name: Check rate limits
        run: |
          curl -s --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
        shell: bash

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install remotes
        run: |
          if (!requireNamespace("curl", quietly = TRUE)) install.packages("curl")
          if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")
        shell: Rscript {0}

      - name: Prepare cache keys
        if: runner.os != 'Windows'
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE, type = .Platform$pkgType), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.config.os }}-${{ hashFiles('.github/R-version') }}-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ matrix.config.os }}-${{ hashFiles('.github/R-version') }}-2-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "${{matrix.config.os-version}}"))')

      # Begin custom: before install
      # End custom: before install

      - name: Install dependencies
        run: |
          if (!requireNamespace("curl", quietly = TRUE)) install.packages("curl")
          if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")
          remotes::install_deps(dependencies = TRUE, type = .Platform$pkgType)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          if (!requireNamespace("sessioninfo", quietly = TRUE)) install.packages("sessioninfo")
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      # Begin custom: after install
      # Must happen after installing system dependencies,
      # https://github.com/ankane/setup-mariadb/issues/2
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: 13

      - name: Create database
        if: runner.os != 'Windows'
        run: |
          createdb ${USER}

      - name: Create database
        if: runner.os == 'Windows'
        run: |
          createdb ${USERNAME}
        shell: bash
      # End custom: after install

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
          _R_CHECK_SYSTEM_CLOCK_: false
          _R_CHECK_FUTURE_FILE_TIMESTAMPS_: false
        run: |
          error_on <- "note"
          # Begin custom: rcmdcheck error_on
          error_on <- "warning"
          # End custom: rcmdcheck error_on
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = error_on, check_dir = "check")
        shell: Rscript {0}

      - name: Show test output
        if: always()
        run: find check -name '*.Rout*' -exec head -n 1000000 '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Check rate limits
        if: always()
        run: |
          curl -s --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
        shell: bash
